steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-demo-notes/flask-demonotes-app:${COMMIT_SHA}', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-demo-notes/flask-demonotes-app:${COMMIT_SHA}']
# Create a Cloud Deploy release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - deploy
  - releases
  - create
  - release-$SHORT_SHA
  - --region=us-central1                 # IMPORTANT: Confirm this is your Cloud Deploy pipeline's region
  - --delivery-pipeline=notes-app-pipeline
  - --images=flask-demonotes-app=us-central1-docker.pkg.dev/$PROJECT_ID/flask-demo-notes/flask-demonotes-app:$SHORT_SHA # Pass the image
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-demo-notes/flask-demonotes-app:${COMMIT_SHA}'
options:
 logging: CLOUD_LOGGING_ONLY
