apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: notes-app-pipeline

profiles:
- name: dev
  manifests:
    rawYaml:
    - dev.yaml
  deploy:
    cloudrun: {}

- name: prod
  manifests:
    rawYaml:
    - prod.yaml
  deploy:
    cloudrun: {}
